### ISSUE TITLE
After successful installation, page is redirected to the installer page

### ISSUE THREAD

**Issue by proy2001** [care2x/2.7#11]
I tried to install it today but after successful installation, page is redirected to the installer page again. How to solve this?

**Comment by timschofield** [comment]
Hi, try renaming the installer/install.php to _install.php

Thanks
Tim

**Comment by proy2001** [comment]
after installation it was already renamed to _install.php. The problem is from the index.php page it is redirected to installer directory..

**Comment by timschofield** [comment]
The problem is that _install.php incorrectly existed before the installation, meaning the installer cannot rename it.
So, delete the current _install.php file and then rename install.php to _install.php

Tim

**Comment by timschofield** [comment]
The problem is that _install.php incorrectly existed before the installation, meaning the installer cannot rename it.
So, delete the current _install.php file and then rename install.php to _install.php. I have fixed this in the repository.

Tim

**Comment by proy2001** [comment]
I did a fresh installation... before installing I deleted _install.php file. 
Still after installation is complete, browser redirects to /installer/install.php?restart_installer=true
and shows file not found..

**Comment by timschofield** [comment]
Ok, another possibility is that the file include/core/inc_init_main.php doesn't have the correct database access details setup, the following variables should be correct 
$dbname;
$dbusername
$dbpassword;
$dbhost
can you check them?

**Comment by proy2001** [comment]
Yes, after making correction there.. it works.. Thanks.
However,  as admin if I create a new role, it does not get saved..

**Comment by timschofield** [comment]
Ok, can you create a separate issue for that please
